/// A value for disambiguating commands
///
/// A [Handle[ is guaranteed to be unique within those generated by a given [CommandMultiplexer](crate::CommandMultiplexer)
pub type Handle = usize;

#[derive(Debug, Default)]
pub(crate) struct HandleAllocator(Handle);

impl HandleAllocator {
    pub fn next(&mut self) -> Handle {
        let h = self.0;
        self.0 += 1;
        h
    }
}
